# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Jithin Zacharia
tagline:          'A Jekyll theme'
description:      'Full Stack developer and Technology enthusiast'
url:              https://jithinqw.github.io
baseurl:          /

author:
  name:           'Jithin Zacharia'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Jithinqw
